{% set name = "pygments" %}
{% set version = "2.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Pygments-{{ version }}.tar.gz
  sha256: b3ed06a9e8ac9a9aae5a6f5dbe78a8a58655d17b43b93c078f094ddc476ae297

build:
  number: 0
  noarch: python
  entry_points:
    - pygmentize = pygments.cmdline:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.5

test:
  imports:
    - pygments
    - pygments.filters
    - pygments.formatters
    - pygments.lexers
    - pygments.styles
  requires:
    - pip
  commands:
    - pip check
    - pygmentize -h


about:
  home: https://pygments.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pygments is a generic syntax highlighter suitable for use in code hosting, forums, wikis or other applications that need to prettify source code.
  dev_url: https://github.com/pygments/pygments
  doc_url: https://pygments.org/docs/

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - scopatz
