{% set version = "2.4.1" %}

package:
  name: pygments
  version: {{ version }}

source:
  fn: Pygments-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pygments/Pygments-{{ version }}.tar.gz
  sha256: b437bc0d04dc36f1f5b3592985b3e0a3d0af46b7c39199231706d19a4ee63344

build:
  noarch: python
  number: 0
  entry_points:
    - pygmentize = pygments.cmdline:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - setuptools

test:
  imports:
    - pygments.styles
    - pygments
    - pygments.lexers
    - pygments.filters
    - pygments.formatters
    - pygments.plugin

  commands:
    - pygmentize -h

about:
  home: http://pygments.org/
  license: BSD 2-clause
  license_file: LICENSE
  summary: "Pygments is a generic syntax highlighter suitable for use in code hosting, forums, wikis or other applications that need to prettify source code."

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - scopatz
