travis:
  secure:
    BINSTAR_TOKEN: IUueecYwUw0ceeJ3Z5Yf2jZYL5Sra+QGPhHFmYDNpz5Wr5DD+Yz+QOWOKfLkt61YrUbDNQ72ot+WGq0Hu8iZgFI3dYIxGadFz2ZV0pqIwVnEJqn91H+TJE3M9SBbc50V5lShoritr7Li0h2PMLElUkBx84aIJA5MCTqp284nBSmeVFAKBcwH2tbGOWK9cog+gVv8TCl0YqniIBmT62BhqfOETRV34qmllwvTflXIG0yfBMVrqvbVFdowTMty05md79yfizDWLg6Yyt3N9rKKb26uyVrcn8K8qcZhODYswCX43Rfy5LXDJwUi45w0j3vRZquyfX7BOB/gyLn24jt6Ia6MznPP7Vbf2qSktsMRx7mPBGZYPtA/9V+6KhKj8nsvXbspT7VppYbPEMH5KpD48V/CAXWMIM2AFcgQWiF6uKmNVu9lWVrhDKquaskSlMxhQXw7/gk6lu3wN29s2MRMjMQ89/VYrirO+2/xuHYAHVz3ckPTtfaooFUYykwB2QiBBL+D5hnCEFSDIng83/ng5Nzx0l+1sJkgaJYOCR0320ko3/DkfaPftC6dPWdSpWLF35VgTxusSlTH0RuBaWHW4AwyoXQ/YY9DQGytYzfllEBhfDczvw0pnhByXqWOVHAhR6SHdkHc+R4zNLq6BnW92XVV4W5dPKiMpBUg0aW42DE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
