travis:
  secure:
    BINSTAR_TOKEN: AiFg/c1haexKOoMbEIB36AD9tq3PbhbxdjFwKuwFHcQ1dM22+zIuhI82tmE5KoCDfUkolJhEYK0bRPO9HDLnJ5IooBAd+YXJAPOsx7vYJygVqoMh6rQqaTK+rdiOzQTqqvRdFnKg1mTW8DOa7QRO35duermo+Cnqo6d4Btb7IN3QhDZKs2FrX0rMBUEaYQZv0dtA2OR0gjyWbbOKWGWz6wPR3gqeyqADqbqH60xYPhF/qSP3nKsmhvxw8LJTBhCavFg8pYo0AKadBz427WrdvGVo1AcxPYMlskhh1DKtt1Jd5CKuNsWc06L48EFHvdnoEwQBiaECjrrYTOqbYeqDMI4MGdDA16q+c34Q0NQNQO5YQypzmemqrHuRoThy5QV1Ekw3Xyjwhq1irnjgYg2ZlgDkXH7o0r2VufcGUA61qnUpELysjQXHNPbN+EB0J7PgfNRnwHgxGcCf5saxxjHErOgVA0jy/dpN6Xu7HptZ0R3BO091q8ESgxlqN2kwSIUIWE4WK8I9elrXcX21JurxnTzQcG9rGZ43r5KKapMamrgqh5x26tPYY11sEJqHdv9jKDS6VAOEknUEgNCEJCpdWXAz/WfuEAciQb9vtLy/pm49c4sgi2yxuqrJq7ydqLvToSKIW7QRL1sN6ZR0mhnJCrpLsaHIFVxAhpVorZRFkJg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
