travis:
  secure:
    BINSTAR_TOKEN: TtUsH4I54xOU/NSrdEBQ5l3pHUTR88pHEre/UqCANvSpRvBDmxcNMoORiiANT3Kh9rOGGHPplXm6zYRk8TPZw5fbnaRaaRp0G3PcBSrqtFwmFSuUaIJNXvQ5HhJ7C9oWGzLFqD4BEtvc70dI/0Ju9xtK2HFeQOoQnL5mW5EbLbZVAhc0whLCiX+C2RhHZdI89nzx0Zc67y/UGCQr2xoCExMlV4T1wzzoLsErX/aJbifpEYdlNyU4kHv8vkkeJdsKG6C3llJhytE/m00yaCRhEcTdoedHSgAaVCpy0LnmPqvVuIwDIwof41XlKf4K1xgywZzo9MBFUjiZZX5P9iCZdbZB8rxSH/o6E3JIDZ95j6GwEtW/sc/9Uz6Np41y5040TN4vNqXOJYNARmMq0+yyMxKpljquf+STCsRuozXDMSEXpHm8kYKsC1j4q2171CCTTc5O7gnziMGpcdsGVsapUP4KnMYS4UqV2tgGMvNy4+qrdG+Yh3pz1Pv4XxViOIGb9+TEiRr1emqm5KVTJ0UPf9cd22/2FNa3FHBUEd3k6cZ62TfgV/43rQEjjLSRCt7VjlkuHNuJdz4wf4owYUJNRAKl5ISjG2peGZCqsAScSTqtOMAanjJrqX4HEzB+jsX+KoIPveefAVvnWQbVZDR4b4/Vbi5hJQfRHVfRL6rTRII=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
